BohoTours/Web/BohoTours.Web/Controllers/BookingsController.cs
namespace BohoTours.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using BohoTours.Services.Data.Bookings;
    using BohoTours.Services.Data.Hotels;
    using BohoTours.Services.Data.Vacations;
    using BohoTours.Web.ViewModels.Bookings;
    using BohoTours.Web.ViewModels.Hotels;
    using BohoTours.Web.ViewModels.Vacations;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class BookingsController : BaseController
    {
        private readonly IBookingsService bookingsService;
        private readonly IVacationsService vacationsService;
        private readonly IHotelsService hotelsService;

        public BookingsController(IBookingsService bookingsService, IVacationsService vacationsService, IHotelsService hotelsService)
        {
            this.bookingsService = bookingsService;
            this.vacationsService = vacationsService;
            this.hotelsService = hotelsService;
        }

        [Authorize]
        public IActionResult BookHotel(int id)
        {
            var hotel = this.hotelsService.GetById<SingleHotelViewModel>(id);

            return this.View(hotel.HotelRooms);
        }

        [Authorize]
        public IActionResult BookVacation(int id)
        {
            var vacation = this.vacationsService.GetById<SingleVacationViewModel>(id);

            return this.View(vacation.VacationPrices);
        }

        [Authorize]
        public IActionResult AddHotelBooking([FromQuery] int modelId, int modelPriceId, int price, DateTime startDate)
        {
            var (hotelName, roomType) = this.hotelsService.GetRoomInfo(modelPriceId);

            var booking = new CreateHotelBookingViewModel
            {
                EntityPriceId = modelPriceId,
                Price = price,
                StartDate = startDate,
                RoomType = roomType,
                HotelName = hotelName,
                EntityId = modelId,
            };

            return this.View(booking);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> AddHotelBooking([FromForm] CreateHotelBookingViewModel viewModel)
        {
            await this.bookingsService.Create(viewModel);

            return this.Redirect("/Bookings/Success");
        }

        [Authorize]
        public IActionResult AddVacationBooking(int modelId, int modelPriceId, int price, DateTime startDate)
        {
            var vacation = this.vacationsService.GetById<SingleVacationViewModel>(modelId);

            var booking = new CreateVacationBookingViewModel
            {
                EntityPriceId = modelPriceId,
                Price = price,
                VacantionName = vacation.Name,
                VacantionDuration = vacation.Duration,
                StartDate = startDate,
                EntityId = modelId,
            };

            return this.View(booking);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> AddVacationBooking([FromForm] CreateVacationBookingViewModel viewModel)
        {
            await this.bookingsService.Create(viewModel);

            return this.Redirect("/Bookings/Success");
        }

        public IActionResult Success()
        {
            return this.View();
        }
    }
}

BohoTours/Web/BohoTours.Web/Controllers/HotelsController.cs
namespace BohoTours.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using BohoTours.Data.Models;
    using BohoTours.Services.Data;
    using BohoTours.Services.Data.Hotels;
    using BohoTours.Web.ViewModels.Feedbacks;
    using BohoTours.Web.ViewModels.Hotels;
    using BohoTours.Web.ViewModels.Towns;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Routing;

    public class HotelsController : Controller
    {
        private readonly IHotelsService hotelsService;
        private readonly ITownsService townsService;

        public HotelsController(IHotelsService hotelsService, ITownsService townsService)
        {
            this.hotelsService = hotelsService;
            this.townsService = townsService;
        }

        public IActionResult All(string town, string searchTerm, Sorting sorting, int id = 1)
        {
            var itemsPerPage = 12;

            var hotels = this.hotelsService.GetAll<HotelInListViewModel>().AsQueryable();
            var hotelsCount = this.hotelsService.GetCount();

            if (sorting != 0)
            {
                hotels = sorting switch
                {
                    Sorting.Name => hotels.OrderBy(x => x.Name),
                    Sorting.PriceAsc => hotels.OrderBy(x => x.RoomMinPrice),
                    Sorting.PriceDesc => hotels.OrderByDescending(x => x.RoomMinPrice),
                    Sorting.Country => hotels.OrderBy(x => x.TownName),
                    _ => hotels,
                };
            }

            if (!string.IsNullOrWhiteSpace(town) || !string.IsNullOrWhiteSpace(searchTerm))
            {
                if (!string.IsNullOrWhiteSpace(town))
                {
                    hotels = hotels.Where(x => x.TownName == town).AsQueryable();
                }

                if (!string.IsNullOrWhiteSpace(searchTerm))
                {
                    hotels = hotels.Where(x =>
                        x.Name.ToLower().Contains(searchTerm.ToLower()) ||
                        x.CountryName.ToLower().Contains(searchTerm.ToLower()) ||
                        x.TownName.ToLower().Contains(searchTerm.ToLower())).AsQueryable();
                }

                hotelsCount = hotels.Count();
            }

            hotels = hotels.Skip((id - 1) * itemsPerPage).Take(itemsPerPage);

            var towns = this.townsService.GetAll<TownViewModel>().Select(x => x.Name);

            var viewModel = new HotelsListViewModel()
            {
                ItemsPerPage = 12,
                PageNumber = id,
                Hotels = hotels,
                HotelCount = hotelsCount,
                SearchTerm = searchTerm,
                Towns = towns,
                Town = town,
                Sorting = sorting,
            };

            return this.View(viewModel);
        }

        public IActionResult Details(int id, FeedbackViewModel feedback)
        {
            if (feedback.ModelId != 0)
            {
                id = feedback.ModelId;
            }

            var hotel = this.hotelsService.GetById<SingleHotelViewModel>(id);

            if (feedback == null)
            {
                hotel.Feedback = new FeedbackViewModel();
            }
            else
            {
                hotel.Feedback = feedback;
            }

            this.ViewData["Title"] = hotel.Name;

            return this.View(hotel);
        }

        [HttpPost]
        public async Task<IActionResult> LeaveFeedback(FeedbackViewModel feedback)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction($"Details", new RouteValueDictionary(feedback));
            }

            await this.hotelsService.AddFeedback(feedback);
            return this.RedirectToAction($"Details", new { id = feedback.ModelId });
        }

        public IActionResult Reviews(int id)
        {
            var ratings = this.hotelsService.GetReviews<HotelRatingsReviewViewModel>(id);

            var ratingInfo = new HotelRatingsViewModel()
            {
                HotelName = this.hotelsService.GetById<SingleHotelViewModel>(id).Name,
                HotelRatingsReviews = ratings.ToList(),
                Rating = ratings.ToList().Average(x => x.Rating),
                RatingsCount = ratings.Count(),
            };

            return this.View(ratingInfo);
        }
    }
}

BohoTours/Web/BohoTours.Web/Controllers/VacationsController.cs
namespace BohoTours.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using BohoTours.Data.Models;
    using BohoTours.Services.Data;
    using BohoTours.Services.Data.Transports;
    using BohoTours.Services.Data.Vacations;
    using BohoTours.Web.ViewModels.Countries;
    using BohoTours.Web.ViewModels.Feedbacks;
    using BohoTours.Web.ViewModels.Towns;
    using BohoTours.Web.ViewModels.Vacations;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Routing;

    public class VacationsController : Controller
    {
        private readonly ICountriesService countriesService;
        private readonly ITownsService townsService;
        private readonly IVacationsService vacationsService;

        public VacationsController(ICountriesService countriesService, ITownsService townsService, IVacationsService vacationsService)
        {
            this.countriesService = countriesService;
            this.townsService = townsService;
            this.vacationsService = vacationsService;
        }

        public IActionResult All(int country, int[] towns, string searchTerm, Sorting sorting, int id = 1)
        {
            var itemsPerPage = 12;

            var vacations = this.vacationsService.GetAll<VacationInListViewModel>().AsQueryable();
            var vacationsCount = this.vacationsService.GetCount();

            if (sorting != 0)
            {
                vacations = sorting switch
                {
                    Sorting.Name => vacations.OrderBy(x => x.Name),
                    Sorting.PriceAsc => vacations.OrderBy(x => x.VacationMinPrice),
                    Sorting.PriceDesc => vacations.OrderByDescending(x => x.VacationMinPrice),
                    Sorting.Country => vacations.OrderBy(x => x.CountryName),
                    _ => vacations,
                };
            }

            if (country != 0 || !string.IsNullOrWhiteSpace(searchTerm) || towns.Length != 0)
            {
                if (country != 0)
                {
                    vacations = vacations.Where(x => x.CountryId == country).AsQueryable();
                }

                if (!string.IsNullOrWhiteSpace(searchTerm))
                {
                    vacations = vacations.Where(x =>
                        x.Name.ToLower().Contains(searchTerm.ToLower()) ||
                        x.CountryName.ToLower().Contains(searchTerm.ToLower())).AsQueryable();
                }

                if (towns.Length != 0)
                {
                    var townsListSelected = new List<string>();

                    foreach (var townId in towns)
                    {
                        townsListSelected.Add(this.townsService.GetAll<TownViewModel>().Where(x => x.Id == townId).Select(x => x.Name).FirstOrDefault());
                    }

                    vacations = vacations.Where(x => x.TownsVisited.Split(", ", StringSplitOptions.RemoveEmptyEntries).Intersect(townsListSelected).Count() == townsListSelected.Count);
                }

                vacationsCount = vacations.Count();
            }

            vacations = vacations.Skip((id - 1) * itemsPerPage).Take(itemsPerPage);

            var countries = this.countriesService.GetAll<CountryViewModel>().Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
            });
            var townsListToAdd = this.townsService.GetAll<TownViewModel>().Where(x => x.CountryId == country).Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
            });

            var viewModel = new VacationsListViewModel()
            {
                ItemsPerPage = 12,
                PageNumber = id,
                Vacations = vacations,
                VacationsCount = vacationsCount,
                SearchTerm = searchTerm,
                Country = country,
                Countries = countries,
                Sorting = sorting,
                TownsList = townsListToAdd,
                SelectedTowns = towns,
            };

            return this.View(viewModel);
        }

        public IActionResult Details(int id, FeedbackViewModel feedback)
        {
            if (feedback.ModelId != 0)
            {
                id = feedback.ModelId;
            }

            var vacation = this.vacationsService.GetById<SingleVacationViewModel>(id);

            if (feedback == null)
            {
                vacation.Feedback = new FeedbackViewModel();
            }
            else
            {
                vacation.Feedback = feedback;
            }

            this.ViewData["Title"] = vacation.Name;

            return this.View(vacation);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> LeaveFeedback(FeedbackViewModel feedback)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction($"Details", new RouteValueDictionary(feedback));
            }

            await this.vacationsService.AddFeedback(feedback);
            return this.RedirectToAction($"Details", new { id = feedback.ModelId });
        }

        public IActionResult Reviews(int id)
        {
            var ratings = this.vacationsService.GetReviews<VacationRatingsReviewViewModel>(id);

            var ratingInfo = new VacationRatingsViewModel
            {
                HotelName = this.vacationsService.GetById<SingleVacationViewModel>(id)
                    .Name,
                HotelRatingsReviews = ratings.ToList(),
                Rating = ratings.ToList()
                    .Average(x => x.Rating),
                RatingsCount = ratings.Count(),
            };

            return this.View(ratingInfo);
        }
    }
}

BohoTours/Web/BohoTours.Web/Views/Shared/_Layout.cshtml
@using BohoTours.Common
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.14/css/bootstrap-select.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Gideon+Roman&display=swap" rel="stylesheet">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-map" style="color: #31bfb1"></i> Boho<b>Tours</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li is-active-route asp-controller="Vacations" asp-action="All" class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Vacations" asp-action="All" asp-route-id="1">Vacations <span class="sr-only">(current)</span></a>
                    </li>
                    <li is-active-route class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Hotels" asp-action="All" asp-route-id="1">Hotels</a>
                    </li>
                    @if (this.User.IsInRole("Administrator"))
                    {
                        <li is-active-route class="nav-item">
                            <a class="nav-link" asp-area="Administration"  asp-controller="Hotels" asp-action="Create">Add Hotel</a>
                        </li>
                        <li is-active-route class="nav-item">
                            <a class="nav-link" asp-area="Administration"  asp-controller="Vacations" asp-action="Create">Add Vacation</a>
                        </li>
                        <li is-active-route class="nav-item">
                            <a class="nav-link" asp-area="Administration" asp-controller="Bookings" asp-action="AllHotelBookings">Hotel Bookings</a>
                        </li>
                        <li is-active-route class="nav-item">
                            <a class="nav-link" asp-area="Administration" asp-controller="Bookings" asp-action="AllVacationBookings">Vacation Bookings</a>
                        </li>
                    }
                </ul>
                <ul class="nav justify-content-end ">
                    @if (!this.User.Identity.IsAuthenticated)
                    {

        <li>
            <a data-toggle="dropdown" class="nav-link mt-1" href="#"><i class="fa fa-user"> Login</i></a>
            <ul class="dropdown-menu form-wrapper">
                <li>
                    <form asp-area="Identity" asp-page="/Account/Login" asp-route-returnUrl="/Home/Index" method="post">
                        <p class="hint-text">Sign in with your social media account</p>
                        <div class="form-group social-btn clearfix">
                            <a href="#" class="btn btn-primary pull-left"><i class="fa fa-facebook"></i> Facebook</a>
                            <a href="#" class="btn btn-info pull-right"><i class="fa fa-twitter"></i> Twitter</a>
                        </div>
                        <div class="or-seperator"><b>or</b></div>
                        <div class="form-group">
                            <input type="email" name="email" class="form-control" placeholder="Username" required="required">
                        </div>
                        <div class="form-group">
                            <input type="password" name="password" class="form-control" placeholder="Password" required="required">
                        </div>
                        <input type="submit" class="btn btn-primary btn-block" value="Login">
                        <div class="form-footer">
                            <a href="#">Forgot Your password?</a>
                        </div>
                    </form>
                </li>
            </ul>
        </li>
                        <li>
                            <a href="#" id="signIn" data-toggle="dropdown" class="btn btn-primary get-started-btn mt-1 mb-1"><i class="fa fa-id-card"> Sign up</i></a>
                            <ul class="dropdown-menu form-wrapper">
                                <li>
                                    <form asp-area="Identity" asp-page="/Account/Register" asp-route-returnUrl="/Home/Index" method="post">
                                        <p class="hint-text">Fill in this form to create your account!</p>
                                        <div class="form-group">
                                            <input type="email" name="email" class="form-control" placeholder="Username" required="required">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="password" class="form-control" placeholder="Password" required="required">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="confirmPassword" class="form-control" placeholder="Confirm Password" required="required">
                                        </div>
                                        <div class="form-group">
                                            <label class="checkbox-inline"><input type="checkbox" required="required"> I accept the <a href="#">Terms &amp; Conditions</a></label>
                                        </div>
                                        <input type="submit" class="btn btn-primary btn-block" value="Sign up">
                                    </form>
                                </li>
                            </ul>
                        </li> }
                                    else
                                    {
                        <li class="nav-item dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle user-action"><img src="https://www.tutorialrepublic.com/examples/images/avatar/2.jpg" class="avatar" alt="Avatar"> @User.Identity.Name<b class="caret"></b></a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a href="#" class="dropdown-item"><i class="fa fa-user-o"></i> Profile</a>
                                <a href="#" class="dropdown-item"><i class="fa fa-calendar-o"></i> My bookings</a>
                                <a href="#" class="dropdown-item"><i class="fa fa-calendar-o"></i> Clients bookings</a>
                                <a href="#" class="dropdown-item"><i class="fa fa-sliders"></i> Settings</a>
                                <div class="dropdown-divider"></div>
                                <a href="javascript:{}" onclick="document.getElementById('logout').submit();return false;" class="dropdown-item"><i class="material-icons">&#xE8AC;</i> Logout</a>
                                <form id="logout" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/" method="post">
                                </form>
                            </div>
                        </li>}
                </ul>


            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
        <footer class="navbar navbar-default navbar-footer navbar-expand-lg navbar-light">
            <div class="footer-top">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <h4>About us</h4>
                            <p>
                                We are a young company always looking for new and creative ideas to help you with our products in your everyday work.
                            </p>
                            <p>© Company Inc.</p>
                        </div>
                        <div class="col-md-4">
                            <h4>Contact</h4>
                            <p><i class="fas fa-map-marker-alt" style="color: #31bfb1"></i> Via Rossini 10, 10136 Turin Italy</p>
                            <p><i class="fas fa-phone" style="color: #31bfb1"></i> Phone: (0039) 333 12 68 347</p>
                            <p><i class="fas fa-envelope" style="color: #31bfb1"></i> Email: <a href="mailto:hello@domain.com">hello@domain.com</a></p>
                            <p><i class="fab fa-skype" style="color: #31bfb1"></i> Skype: you_online</p>
                        </div>
                        <div class="col-md-4">
                            <div class="row">
                                <div class="col">
                                    <h4>Links</h4>
                                    <p><a href="#">Home</a></p>
                                    <p><a href="#">Features</a></p>
                                    <p><a href="#">How it works</a></p>
                                    <p><a href="#">Our clients</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <ul class="nav justify-content-center">
                    <li class="nav-item m-1">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                    </li>
                    <li class="nav-item m-1">
                        <a href="#"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li class="nav-item m-1">
                        <a href="#"><i class="fab fa-google-plus-g"></i></a>
                    </li>
                    <li class="nav-item m-1">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </li>
                    <li class="nav-item m-1">
                        <a href="#"><i class="fab fa-pinterest"></i></a>
                    </li>
                </ul>
            </div>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.0.4/popper.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.14/js/bootstrap-select.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/e3daaa3d52.js" crossorigin="anonymous"></script>


    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>