BohoTours/Web/BohoTours.Web/Areas/Administration/Controllers/VacationsController.cs
namespace BohoTours.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using BohoTours.Services.Data;
    using BohoTours.Services.Data.Transports;
    using BohoTours.Services.Data.Vacations;
    using BohoTours.Web.ViewModels.Continenst;
    using BohoTours.Web.ViewModels.Countries;
    using BohoTours.Web.ViewModels.Towns;
    using BohoTours.Web.ViewModels.Transports;
    using BohoTours.Web.ViewModels.Vacations;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;

    public class VacationsController : AdministrationController
    {
        private readonly ICountriesService countriesService;
        private readonly IContinentsService continentsService;
        private readonly ITownsService townsService;
        private readonly ITransportsService transportsService;
        private readonly IVacationsService vacationsService;

        public VacationsController(IContinentsService continentsService, ICountriesService countriesService, ITownsService townsService, IVacationsService vacationsService, ITransportsService transportsService)
        {
            this.continentsService = continentsService;
            this.countriesService = countriesService;
            this.townsService = townsService;
            this.vacationsService = vacationsService;
            this.transportsService = transportsService;
        }

        public IActionResult Create()
        {
            var viewModel = new CreateVacationViewModel()
            {
                Countries = this.countriesService.GetAll<CountryViewModel>().Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString(),
                }),
                Continents = this.continentsService.GetAll<ContinentViewModel>()
                    .Select(x => new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.Id.ToString(),
                    }),
                Transports = this.transportsService.GetAll<TransportViewModel>().Select(x => new SelectListItem()
                {
                    Text = x.TransportType,
                    Value = x.Id.ToString(),
                }),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateVacationViewModel vacation)
        {
            if (!vacation.VacationPrices.Any(x => !x.IsDeleted))
            {
                this.ModelState.AddModelError(nameof(CreateVacationViewModel.VacationPrices), "Vacation must have at least one price");
            }

            var errors = this.ModelState.ErrorCount;

            if (!this.ModelState.IsValid || errors != 0)
            {
                vacation.Transports = this.transportsService.GetAll<TransportViewModel>().Select(x => new SelectListItem()
                {
                    Text = x.TransportType,
                    Value = x.Id.ToString(),
                });
                vacation.Countries = this.countriesService.GetAll<CountryViewModel>().Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString(),
                });
                vacation.Continents = this.continentsService.GetAll<ContinentViewModel>()
                    .Select(x => new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.Id.ToString(),
                    });

                if (vacation.CountryId != 0)
                {
                    vacation.CountryName = vacation.Countries.FirstOrDefault(x => x.Value == vacation.CountryId.ToString()).Text;
                    vacation.Towns = this.townsService.GetAll<TownViewModel>().Where(t => t.CountryId == vacation.CountryId).Select(x => new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.Id.ToString(),
                    });
                }

                vacation.Countries = vacation.Countries.Where(x => x.Value != vacation.CountryId.ToString());
                return this.View(vacation);
            }

            var vacationId = await this.vacationsService.Create(vacation);

            return this.Redirect($"/Vacations/Details/{vacationId}");
        }

        public IActionResult Edit(int id)
        {
            var vacation = this.vacationsService.GetById<EditVacationViewModel>(id);

            vacation.Continents = this.continentsService.GetAll<ContinentViewModel>().Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
            }).ToList();
            vacation.Countries = this.countriesService.GetAll<CountryViewModel>().Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
            }).ToList();
            vacation.VacationPrices = vacation.VacationPrices.Where(x => !x.IsDeleted).Select(x => new VacationPriceViewModel()
            {
                Id = x.Id,
                Date = x.Date,
                Price = x.Price,
            }).ToList();

            vacation.Transports = this.transportsService.GetAll<TransportViewModel>().Select(x => new SelectListItem()
            {
                Text = x.TransportType,
                Value = x.Id.ToString(),
            }).ToList();

            vacation.Towns = this.townsService.GetAll<TownViewModel>().Where(x => x.CountryId == vacation.CountryId).Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
            }).ToList();

            vacation.ImportedImages = vacation.ImportedImages.Where(x => !x.IsImageDeleted).ToList();

            return this.View(vacation);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditVacationViewModel vacation)
        {
            if (!vacation.VacationPrices.Any(x => !x.IsDeleted))
            {
                this.ModelState.AddModelError(nameof(EditVacationViewModel.VacationPrices), "Vacation must have at least one price");
            }

            if (!vacation.ImportedImages.Any(x => !x.IsImageDeleted))
            {
                this.ModelState.AddModelError(nameof(EditVacationViewModel.ImportedImages), "Hotel must have at least one image");
            }

            var errors = this.ModelState.ErrorCount;

            if (!this.ModelState.IsValid || errors != 0)
            {
                vacation.Countries = this.countriesService.GetAll<CountryViewModel>().Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString(),
                });
                vacation.Continents = this.continentsService.GetAll<ContinentViewModel>()
                    .Select(x => new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.Id.ToString(),
                    });
                vacation.Transports = this.transportsService.GetAll<TransportViewModel>().Select(x => new SelectListItem()
                {
                    Text = x.TransportType,
                    Value = x.Id.ToString(),
                }).ToList();

                vacation.Towns = this.townsService.GetAll<TownViewModel>().Where(x => x.CountryId == vacation.CountryId).Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString(),
                }).ToList();

                if (vacation.CountryId != 0)
                {
                    vacation.CountryName = vacation.Countries.FirstOrDefault(x => x.Value == vacation.CountryId.ToString()).Text;
                }

                vacation.Countries = vacation.Countries.Where(x => x.Value != vacation.CountryId.ToString());
                return this.View(vacation);
            }

            await this.vacationsService.Edit(vacation);

            return this.Redirect($"/Vacations/Details/{vacation.Id}");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.vacationsService.Delete(id);

            return this.Redirect($"/Vacations/All");
        }
    }
}

BohoTours/Web/BohoTours.Web/Controllers/BookingsController.cs
namespace BohoTours.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using BohoTours.Services.Data.Bookings;
    using BohoTours.Services.Data.Hotels;
    using BohoTours.Services.Data.Vacations;
    using BohoTours.Web.ViewModels.Bookings;
    using BohoTours.Web.ViewModels.Hotels;
    using BohoTours.Web.ViewModels.Vacations;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class BookingsController : BaseController
    {
        private readonly IBookingsService bookingsService;
        private readonly IVacationsService vacationsService;
        private readonly IHotelsService hotelsService;

        public BookingsController(IBookingsService bookingsService, IVacationsService vacationsService, IHotelsService hotelsService)
        {
            this.bookingsService = bookingsService;
            this.vacationsService = vacationsService;
            this.hotelsService = hotelsService;
        }

        [Authorize]
        public IActionResult BookHotel(int id)
        {
            var hotel = this.hotelsService.GetById<SingleHotelViewModel>(id);

            return this.View(hotel.HotelRooms);
        }

        [Authorize]
        public IActionResult BookVacation(int id)
        {
            var vacation = this.vacationsService.GetById<SingleVacationViewModel>(id);

            return this.View(vacation.VacationPrices);
        }

        [Authorize]
        public IActionResult AddHotelBooking([FromQuery] int modelId, int modelPriceId, int price, DateTime startDate)
        {
            var (hotelName, roomType) = this.hotelsService.GetRoomInfo(modelPriceId);

            var booking = new CreateHotelBookingViewModel
            {
                EntityPriceId = modelPriceId,
                Price = price,
                StartDate = startDate,
                RoomType = roomType,
                HotelName = hotelName,
                EntityId = modelId,
            };

            return this.View(booking);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> AddHotelBooking([FromForm] CreateHotelBookingViewModel viewModel)
        {
            await this.bookingsService.Create(viewModel);

            return this.Redirect("/Bookings/Success");
        }

        [Authorize]
        public IActionResult AddVacationBooking(int modelId, int modelPriceId, int price, DateTime startDate)
        {
            var vacation = this.vacationsService.GetById<SingleVacationViewModel>(modelId);

            var booking = new CreateVacationBookingViewModel
            {
                EntityPriceId = modelPriceId,
                Price = price,
                VacantionName = vacation.Name,
                VacantionDuration = vacation.Duration,
                StartDate = startDate,
                EntityId = modelId,
            };

            return this.View(booking);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> AddVacationBooking([FromForm] CreateVacationBookingViewModel viewModel)
        {
            await this.bookingsService.Create(viewModel);

            return this.Redirect("/Bookings/Success");
        }

        public IActionResult Success()
        {
            return this.View();
        }
    }
}

BohoTours/Web/BohoTours.Web/ViewComponents/RecommendedVacationsViewComponent.cs
namespace BohoTours.Web.ViewComponents
{
    using BohoTours.Services.Data.Vacations;
    using BohoTours.Web.ViewModels.Vacations;
    using Microsoft.AspNetCore.Mvc;

    public class RecommendedVacationsViewComponent : ViewComponent
    {
        private readonly IVacationsService vacationsService;

        public RecommendedVacationsViewComponent(IVacationsService vacationsService)
        {
            this.vacationsService = vacationsService;
        }

        public IViewComponentResult Invoke()
        {
            var recommendedHotels = this.vacationsService.GetRecommended<VacationInListViewModel>();
            return this.View(recommendedHotels);
        }
    }
}

BohoTours/Web/BohoTours.Web/ViewComponents/VacationRatingsViewComponent.cs
namespace BohoTours.Web.ViewComponents
{
    using System.Linq;

    using BohoTours.Services.Data.Vacations;
    using BohoTours.Web.ViewModels.Vacations;
    using Microsoft.AspNetCore.Mvc;

    public class VacationRatingsViewComponent : ViewComponent
    {
        private readonly IVacationsService vacationsService;

        public VacationRatingsViewComponent(IVacationsService vacationsService)
        {
            this.vacationsService = vacationsService;
        }

        public IViewComponentResult Invoke(InvokeRequest request)
        {
            var ratings = this.vacationsService.GetReviews<VacationRatingsReviewViewModel>(request.Id);

            var ratingInfo = new VacationRatingsViewModel()
            {
                Id = request.Id,
                HotelName = request.VacationName,
                HotelRatingsReviews = ratings.ToList(),
                Rating = ratings.ToList().Average(x => x.Rating),
                RatingsCount = ratings.Count(),
            };

            return this.View(ratingInfo);
        }

        public class InvokeRequest
        {
            public int Id { get; set; }

            public string VacationName { get; set; }
        }
    }
}

BohoTours/Web/BohoTours.Web/Views/Vacations/Details.cshtml
@using BohoTours.Web.ViewModels.Vacations
@using BohoTours.Web.ViewComponents
@model BohoTours.Web.ViewModels.Vacations.SingleVacationViewModel

<div class="blog-single gray-bg">
    <div class="container">
        <h1 class="hotel-title" asp-for="@Model.Name">@Model.Name</h1>
        <div class="row align-items-start">
            <div class="col-lg-8 m-15px-tb">
                <article class="article">
                    <div class="article-img">
                        <div id="demo" class="carousel slide carousel-fade" data-ride="carousel">
                            <div class="carousel-inner rounded">
                                <div class="carousel-item active">
                                    <img class="img-fluid w-100" src="@Model.Images.First()" alt="image">
                                </div>
                                @foreach (var image in Model.Images.Skip(1))
                                {
                                    <div class="carousel-item">
                                        <img class="img-fluid w-100" src="@image" alt="New York">
                                    </div>
                                }
                            </div>
                            <!-- Left and right controls -->
                            <a class="carousel-control-prev" href="#demo" data-slide="prev">
                                <span class="carousel-control-prev-icon"></span>
                            </a>
                            <a class="carousel-control-next" href="#demo" data-slide="next">
                                <span class="carousel-control-next-icon"></span>
                            </a>
                        </div>
                    </div>
                    <div class="small-pictures">
                        @foreach (var image in Model.Images.Take(12))
                        {
                            <img class="myImg" src="@image" alt="image">
                        }
                    </div>
                    <!-- The Modal -->
                    <div id="myModal" class="modal">
                        <!-- The Close Button -->
                        <span class="close">&times;</span>
                        <!-- Modal Content (The Image) -->
                        <img class="modal-content" id="img01">
                    </div>
                </article>
                <article class="article">
                    <h4>Description</h4>
                    <p class="text-justify">@Model.Description</p>
                </article>
                <article class="article">
                    <h4>Vacation Summary</h4>
                    <p class="text-justify">@Model.Summary</p>
                </article>
                <article class="article">
                    <h4>Prices</h4>
                    <h5 class="text-center mt-5 ">Prices per dates:</h5>
                    <table class="table table-bordered table-hover">
                        <thead class="text-center">
                            <tr>
                                <th scope="col">Date</th>
                                <th scope="col">Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var price in Model.VacationPrices.Where(x => !x.IsDeleted))
                            {
                                <tr>
                                    <td>@price.Date.ToShortDateString()</td>
                                    <td>@price.Price.ToString("N2")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </article>
                <div class="contact-form article-comment">
                    <h4>Leave Feedback</h4>
                    <form id="contact-form" method="POST">
                        @if (Model.Feedback.ModelId != 0)
                        {
                            <div asp-validation-summary="All" class="text-danger"></div>
                        }
                        <div class="row">
                            <input hidden name="ModelId" value="@Model.Id" />
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="rating">
                                        <input type="radio" name="rating" value="5" id="5">
                                        <label for="5">☆</label> <input type="radio" name="rating" value="4" id="4">
                                        <label for="4">☆</label> <input type="radio" name="rating" value="3" id="3">
                                        <label for="3">☆</label> <input type="radio" name="rating" value="2" id="2">
                                        <label for="2">☆</label> <input type="radio" name="rating" value="1" id="1">
                                        <label for="1">☆</label>
                                    </div>
                                </div>
                                <span asp-validation-for="Feedback.Rating" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input name="Name" id="name" placeholder="Name *" class="form-control" type="text" value="@Model.Feedback.Name" />
                                    <span asp-validation-for="Feedback.Name" class="text-danger"></span>

                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input name="Email" id="email" placeholder="Email *" class="form-control" type="email" value="@Model.Feedback.Email">
                                    <span asp-validation-for="Feedback.Email" class="text-danger"></span>

                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <textarea name="message" id="message" placeholder="Your message *" rows="4" class="form-control" value="@Model.Feedback.Message"></textarea>
                                    <span asp-validation-for="Feedback.Message" class="text-danger"></span>

                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="send">
                                    <button type="submit" asp-action="LeaveFeedback" asp-route-id="@Model.Id" class="px-btn theme"><span>Submit feedback</span> <i class="arrow"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        <div class="col-lg-4 m-15px-tb blog-aside">
            <div class="widget widget-author">
                <div class="widget-title">
                    <h3>About the vacation</h3>
                </div>
                <div class="widget-body">
                    <div class="mb-3">
                        <strong>Destinations:</strong> @Model.TownsVisited
                    </div>
                    <div class="mb-3">
                        <strong>Country:</strong> @Model.CountryName
                    </div>
                    <div class="mb-3">
                        <strong>Duration:</strong> @Model.Duration days
                    </div>
                    <div class="mb-3">
                        @if (Model.TransportType == "Plane")
                        {
                            <strong>Transport:</strong> <i class="fas fa-plane text-info"></i> @Model.TransportType
                        }
                        else
                        {
                            <strong>Transport:</strong> <i class="fas fa-bus text-info"></i> @Model.TransportType
                        }

                    </div>
                    <div align="center">
                        Prices from:
                        <h2>$@Model.VacationMinPrice</h2>
                        <div>  <a class="btn btn-primary" asp-controller="Bookings" asp-action="BookVacation" asp-route-id="@Model.Id">Book now</a></div>
                    </div>
                    <hr />
                    @if (this.User.IsInRole("Administrator"))
                    {
                        <div class="row m-2">
                            <a class="btn btn-success col-5  ml-3 mr-3" asp-area="Administration" asp-controller="Vacations" asp-action="Edit" asp-route-id="@Model.Id">
                                <i class="fa fa-pencil-square-o"></i>
                                Edit
                            </a>
                            <button type="button" class="btn btn-danger col-5 mr-3" data-id="@Model.Id" data-toggle="modal" data-target="#deleteHotelModal"><i class="fa fa-trash-o"></i> Delete</button>

                        </div>
                    }

                    <!-- Town Modal -->
                    <div class="modal fade" data-backdrop="false" role="dialog" id="deleteHotelModal" tabindex="-2" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Create Town</h5>
                                </div>
                                <div class="modal-body">
                                    <form id="myForm" asp-area="Administration" asp-controller="Vacations" asp-action="Delete">
                                        Are you sure you want to delete this hotel?
                                        <input hidden name="id" value="@Model.Id" />
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal" id="closeTownCreate">Close</button>
                                    <button type="button" class="btn btn-danger" id="modalDeleteButton">Yes, delete it</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            @if (Model.HasReviews)
            {
                @await Component.InvokeAsync("VacationRatings", new VacationRatingsViewComponent.InvokeRequest()
                {
                    VacationName = Model.Name,
                    Id = Model.Id
                })
            }
            else
            {
                <div class="widget widget-post">
                    <div class="widget-title">
                        <h3>Reviews</h3>
                    </div>
                    <div class="widget-body text-center">
                        <h3>No reviews yet</h3>
                    </div>
                </div>
            }
            @await Component.InvokeAsync("RecommendedVacations")
        </div>
    </div>
</div>
</div>

@section Scripts {
    <script>$(document).off('focusin.modal');</script>

    <script>
        $("#modalDeleteButton").click(function () {
            $("#myForm").submit();
        });
    </script>

    <script>
        // Get the modal
        var modal = document.getElementById("myModal");

        // Get the image and insert it inside the modal - use its "alt" text as a caption
        var imgs = document.getElementsByClassName("myImg");
        var modalImg = document.getElementById("img01");
        for (var i = 0; i < imgs.length; i++) {
            imgs[i].onclick = function () {
                modal.style.display = "block";
                modalImg.src = this.src;
            }
        }

        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];

        // When the user clicks on <span> (x), close the modal
        modal.onclick = function () {
            modal.style.display = "none";
        }
    </script>
}

BohoTours/Web/BohoTours.Web/Views/Vacations/Reviews.cshtml
@model BohoTours.Web.ViewModels.Vacations.VacationRatingsViewModel

<div class="container-fluid px-1 py-5 mx-auto">
    <div class="row justify-content-center">
        <div class="col-md-12 text-center mb-5">
            <div class="text-center">
                <div class="ratings">
                    <span class="product-rating">@Model.Rating.ToString("N1")</span><span>/5</span>
                    <div class="stars">
                        @if (Model.Rating >= 1)
                        {
                            <i style="color:#28a745" class="fa fa-star"></i> }
                        else
                        {
                            <i class="fa fa-star"></i>}
                        @if (Model.Rating >= 2)
                        {
                            <i style="color:#28a745" class="fa fa-star"></i> }
                        else
                        {
                            <i class="fa fa-star"></i>}
                        @if (Model.Rating >= 3)
                        {
                            <i style="color:#28a745" class="fa fa-star"></i> }
                        else
                        {
                            <i class="fa fa-star"></i>}
                        @if (Model.Rating >= 4)
                        {
                            <i style="color:#28a745" class="fa fa-star"></i> }
                        else
                        {
                            <i class="fa fa-star"></i>}
                        @if (Model.Rating >= 5)
                        {
                            <i style="color:#28a745" class="fa fa-star"></i> }
                        else
                        {
                            <i class="fa fa-star"></i>}
                    </div>
                    <div class="rating-text"> <span>@Model.RatingsCount ratings & reviews</span> </div>
                    <div> <a class="btn btn-primary mt-2 mb-2" asp-action="Details" asp-route-id="@Model.Id">Back to vacation</a></div>
                </div>
            </div>
            @foreach (var item in Model.HotelRatingsReviews)
            {
                <div class="cardReview">
                    <div class="row d-flex">
                        <div class=""> <img class="profile-pic" src="https://www.pepperhub.in/wp-content/uploads/2020/11/user-male.png"> </div>
                        <div class="d-flex flex-column">
                            <h3 class="mt-2 mb-0">@item.Name</h3>
                            <div>
                                <p class="text-left">
                                    <span class="text-muted mr-2">@item.Rating.ToString("N1")</span>
                                    @if (item.Rating >= 1)
                                    {
                                        <i style="color:#28a745" class="fa fa-star"></i> }
                                    else
                                    {
                                        <i class="fa fa-star"></i>}
                                    @if (item.Rating >= 2)
                                    {
                                        <i style="color:#28a745" class="fa fa-star"></i> }
                                    else
                                    {
                                        <i class="fa fa-star"></i>}
                                    @if (item.Rating >= 3)
                                    {
                                        <i style="color:#28a745" class="fa fa-star"></i> }
                                    else
                                    {
                                        <i class="fa fa-star"></i>}
                                    @if (item.Rating >= 4)
                                    {
                                        <i style="color:#28a745" class="fa fa-star"></i> }
                                    else
                                    {
                                        <i class="fa fa-star"></i>}
                                    @if (item.Rating >= 5)
                                    {
                                        <i style="color:#28a745" class="fa fa-star"></i> }
                                    else
                                    {
                                        <i class="fa fa-star"></i>}
                                </p>
                            </div>
                        </div>
                        <div class="ml-auto">
                            <p class="text-muted pt-5 pt-sm-3">@item.Email</p>
                        </div>
                    </div>
                    <div class="row text-left">
                        <h4 class="blue-text mt-3">"@item.Message"</h4>
                    </div>
                </div>
            }

        </div>
    </div>
</div>