BohoTours/Web/BohoTours.Web/Controllers/HomeController.cs
namespace BohoTours.Web.Controllers
{
    using System.Diagnostics;

    using BohoTours.Web.ViewModels;
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

BohoTours/Web/BohoTours.Web/ViewComponents/ReccomendedIndexViewComponent.cs
namespace BohoTours.Web.ViewComponents
{
    using BohoTours.Services.Data.Hotels;
    using BohoTours.Services.Data.Vacations;
    using BohoTours.Web.ViewModels.Home;
    using BohoTours.Web.ViewModels.Hotels;
    using BohoTours.Web.ViewModels.Vacations;
    using Microsoft.AspNetCore.Mvc;

    public class ReccomendedIndexViewComponent : ViewComponent
    {
        private readonly IHotelsService hotelsService;
        private readonly IVacationsService vacationsService;

        public ReccomendedIndexViewComponent(IHotelsService hotelsService, IVacationsService vacationsService)
        {
            this.hotelsService = hotelsService;
            this.vacationsService = vacationsService;
        }

        public IViewComponentResult Invoke(string continentCode)
        {
            var hotels = this.hotelsService.GetRecommendedByContinent<HotelInListViewModel>(continentCode);
            var vacations = this.vacationsService.GetRecommendedByContinent<VacationInListViewModel>(continentCode);

            var reccomended = new ReccomendedIndexViewModel
            {
                Hotels = hotels,
                Vacations = vacations,
            };

            return this.View(reccomended);
        }
    }
}

BohoTours/Web/BohoTours.Web/Views/Home/Index.cshtml
@using BohoTours.Common
@{ this.ViewData["Title"] = "Travel the world"; }
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="~/css/templatemo-style.css" />
<link rel="stylesheet" href="~/slick/slick.css" />
<link rel="stylesheet" href="~/slick/slick-theme.css" />


<div class="text-center m-2">
    <h1 class="cust-font">Your Journey Begins </h1>
    <p style="color: #5D6362; font-family: 'Gideon Roman', cursive; font-weight: bold ">It's better to see something once then to hear about its thousand times.</p>
</div>
<hr />

<div class="text-center">
    <h2 class="cust-font">Recommended Places</h2>
</div>
<hr />
<div class="tm-container-outer" id="tm-section-3">
    <div class="container">
        <div id="myList" role="tablist">
            <ul class="nav nav-pills tm-tabs-links">
                <li class="tm-tab-link-li">
                    <a class="tm-tab-link" data-toggle="list" href="#namerica" role="tab">
                        <img src="~/img/south-america.png" alt="Image" class="img-fluid">
                        North America
                    </a>
                </li>
                <li class="tm-tab-link-li">
                    <a class="tm-tab-link" data-toggle="list" href="#samerica" role="tab">
                        <img src="~/img/north-america.png" alt="Image" class="img-fluid">
                        South America
                    </a>
                </li>
                <li class="tm-tab-link-li active">
                    <a class="tm-tab-link" data-toggle="list" href="#europe" role="tab">
                        <img src="~/img/europe.png" alt="Image" class="img-fluid">
                        Europe
                    </a>
                </li>
                <li class="tm-tab-link-li">
                    <a class="tm-tab-link" data-toggle="list" href="#asia" role="tab">
                        <img src="~/img/asia.png" alt="Image" class="img-fluid">
                        Asia
                    </a>
                </li>
            </ul>
        </div>

        <div class="tab-content">
            <div class="tab-pane" id="namerica" role="tabpanel">
                <!-- Current Active Tab WITH "show active" classes in DIV tag -->
                <div class="tm-recommended-place-wrap">
                    @await Component.InvokeAsync("ReccomendedIndex", "NA")
                </div>
            </div>
            <div class="tab-pane" id="samerica" role="tabpanel">
                <!-- Current Active Tab WITH "show active" classes in DIV tag -->
                <div class="tm-recommended-place-wrap">
                  @await Component.InvokeAsync("ReccomendedIndex", "SA")

                </div>
            </div>
            <div class="tab-pane active" id="europe" role="tabpanel">
                <!-- Current Active Tab WITH "show active" classes in DIV tag -->
                <div class="tm-recommended-place-wrap">
                @await Component.InvokeAsync("ReccomendedIndex", "EU")

                </div>
            </div>
            <div class="tab-pane" id="asia" role="tabpanel">
                <!-- Current Active Tab WITH "show active" classes in DIV tag -->
                <div>
                  @await Component.InvokeAsync("ReccomendedIndex", "AS")

                </div>
            </div>
        </div>

        <hr />
    </div>
</div>


@section Scripts{ 
<script>

    $('.tm-tab-link-li').click(function () {
        $('.tm-tab-link-li').removeClass('active');
    });
</script>
}